name: build-app
on: workflow_call
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build release image
        run: docker build --tag sudosolve:release .
      - name: Run application
        run: docker run sudosolve:release
