name: build-docs
on: workflow_call
jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Doxygen documentation
        run: |
          mkdir --parents build/docs
          docker run --volume "$(pwd)":/data --rm hrektts/doxygen doxygen Doxyfile
      - name: Upload Doxygen output as artifact
        uses: actions/upload-pages-artifact@v4
        id: deployment
        with:
          path: build/docs/html/
