name: build-docs
on: workflow_call
jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Build Doxygen documentation
        run: |
          mkdir --parents build/docs
          docker run --volume "$(pwd)":/data --rm hrektts/doxygen doxygen Doxyfile
      - name: Upload Doxygen output as artifact
        uses: actions/upload-pages-artifact@v4
        id: doxygen_output
        with:
          path: build/docs/
