name: continuous-integration
on:
  pull_request:
    types: [opened, reopened]
    branchs:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: ./build.sh
